config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  get    '/signup', to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get    '/feed',   to: 'articles#feed'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :articles do
    resource :likes, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :likes, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :title, presence: true
  validates :title, length: { maximum: 50 }
  validates :user_id, presence: true

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :logged_in_user,  only: [:new, :create, :edit, :update, :destroy, :feed]
  before_action :correct_article, only: [:edit, :update, :destroy]
  before_action :store_location,  only: [:index, :feed]
  before_action :can_not_delete,  only: [:destroy]

  def index
    @categories = Category.all
    @q = Article.includes([:user], [:category]).ransack(params[:q])
    @articles = @q.result(distinct: true).page(params[:page]).per(6)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = current_user.articles.build if logged_in?
    @article.title = ""
  end

  def create
    @article = current_user.articles.build(article_params)

    if @article.save
      redirect_to @article, notice: "記事を投稿しました"
    else
      render 'articles/new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article, notice: "記事を更新しました"
    else
      render 'articles/edit'
    end
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    redirect_to session[:forwarding_url] || root_url, notice: "記事を削除しました"
    session.delete(:forwarding_url)
  end

  def feed
    @articles = current_user.feed.includes([:user], [:category]).page(params[:page]).per(6)
  end

  private

    def article_params
      params.require(:article).permit(:title, :content, :category_id)
    end

    def correct_article
      article = Article.find(params[:id])
      unless is_mine?(article) || current_user.admin?
        redirect_to root_url, notice: "このURLにはアクセスできません"
      end
    end

    def can_not_delete
      article = Article.find(params[:id])
      if article.user.test_user? && !current_user.admin?
        redirect_to request.referer, notice: "テストユーザーの投稿は削除できません"
      end
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  require "uri"

  def text_url_to_link(text)
    URI.extract(text, ['http', 'https']).uniq.each do |url|
      sub_text = ""
      sub_text << "<a href=" << url << " target=\"_blank\">" << url << "</a>"
      text.gsub!(url, sub_text)
    end
    text
  end

  def selected_sort
    if params[:q].nil?
      params[:q] = { sorts: 'created_at desc' }
    else
      params[:q][:sorts]
    end
  end
end

app/views/articles/_article_form.erb
<div class="my_container">
  <%= form_with model: @article, local: true do |f| %>
    <p><%= render partial: 'shared/error_messages', locals: { object: f.object } %></p>

    <div class="category_zone">
      <%= f.label :category, 'カテゴリー', {class: 'category_label'} %>
      <div class="category_btns">
        <%= f.collection_radio_buttons(:category_id, Category.all, :id, :name) do |b| %>
          <%= b.label(class: "category_btn") do %>
            <%= b.radio_button %>
            <%= b.text %>
          <% end %>
        <% end %>
      </div>
    </div>

    <%= f.label :title, "タイトル(５０文字以内)" %>
    <%= f.text_area :title, class: "input-text", rows: 3, placeholder: "例：絶対に一度は見るべき映画を紹介します。" %>
    
    <div class="title-counter"><%= @article.title.length%>文字/50文字</div>

    <%= f.label :content, "好きなモノについて紹介してください" %>
    <%= f.text_area :content,  rows: 25 , placeholder: "好きなモノの概要、おすすめポイント等"%>

    <%= f.submit(class: "btn")%>
  <% end %>

</div>

app/views/articles/_landing_page.html.erb
<div class="my_container">
  <div class=introduce_area>
    <div class="balloon">
      <div class="catch_copy"> これ、<br>おすすめ<br>です。</div>
    </div>
    <%= image_tag('mascot.png', alt:'マスコットキャラクター', class: "mascot") %>
  </div>
</div>

<div class=introduce_area>
  <div class="about_me">
    <p class="introduce">SALES TALKは、自分の好きなモノを皆に紹介するwebサービスです。</p>
    <p class="introduce">本や映画、音楽など何でもありです。</p>
    <p class="introduce">営業担当となって、思う存分に売り込んでください！</p>

    <section class="login_area">
      <div class="test_login">
        <%= form_with scope: :session, url: login_path, local: true do |f| %>
          <%= f.hidden_field :email, value: 'test_user@sample.com' %>
          <%= f.hidden_field :password, value: 'test_user_foobar' %>
          <%= f.submit 'テストユーザーとしてログイン', class: "test_login_btn",
                                        data: {confirm: "テストユーザーは\n「アイコン/登録情報の変更」「記事の削除」「退会」\nができません。"} %>
        <% end %>
      </div>      
      <%= link_to signup_path, class: "btn introduce_btn"  do  %>
        <i class="fas fa-user-plus"></i>新規登録
      <% end %>
      <%= link_to login_path, class: "btn introduce_btn"  do  %>
        <i class="fas fa-sign-in-alt"></i>ログイン
      <% end %>
    </section>
  </div>
</div>

app/views/articles/edit.html.erb
<% provide(:title, "記事編集") %>

<div class="link_to_back"><%= link_to "一覧へ戻る", session[:forwarding_url] || root_url %></div>

<div class="section-title">記事の編集</div> 
<%= render partial: 'article_form' %>

<div class="link_to_back"><%= link_to "一覧へ戻る", session[:forwarding_url] || root_url %></div>

app/views/articles/feed.html.erb
<% provide(:title, "タイムライン") %>

<div class="section-title">タイムライン</div> 

<div id="feed">
  <%= render partial: 'shared/articles_grid', locals: { object: @articles } %>
</div>

<div id="paginate">
  <%= paginate @articles, window: 2, left: 1, right: 1 %>
</div>

app/views/articles/index.html.erb
<% provide(:title, "") %>

<%= render partial: 'landing_page' unless logged_in? %>

<div class="section-title">投稿一覧</div> 

<%= search_form_for @q, remote: true do |f| %>
  <div class="keyword_search">
    <%= f.search_field :title_or_content_cont, placeholder: "記事をキーワード検索" %>
  </div>

  <div class="category_search">
    <%= f.label :category_id_eq, 'カテゴリー' %>
    <%= f.collection_select(:category_id_eq, @categories, :id, :name, {:include_blank => '指定なし'}) %>
  </div>

  <div class="sort_search">
    <%= f.label :sorts, '　　表示順' %>
    <%= f.select :sorts, {'最新順': 'created_at desc', 'いいね順': 'likes_count desc' }, { selected: selected_sort } %>
  </div>

  <%= f.button :type => "submit", class: "btn btn-search"  do %>
    <i class="fas fa-search"></i>  検索
  <% end %>
<% end %>

<div id="feed">
  <%= render partial: 'shared/articles_grid', locals: { object: @articles } %>
</div>

<div id="paginate">
  <%= paginate @articles, window: 2, left: 1, right: 1 %>
</div>

app/views/articles/index.js.erb
$('#feed').html("<%= j(render partial: 'shared/articles_grid', locals: { object: @articles }) %>");
$('#paginate').html("<%= j(paginate @articles, window: 2, left: 1, right: 1) %>");

app/views/articles/new.html.erb
<% provide(:title, "新規投稿") %>

<div class="section-title">記事の投稿</div> 

<%= render partial: 'article_form' %>

app/views/articles/show.html.erb
<% provide(:title, "記事詳細") %>

<div class="my_container">

  <div class="category_<%=@article.category.id%>"><%= @article.category.name %></div>

  <p class="title"><%= safe_join(@article.title.split("\n"),tag(:br)) %></p>

  <div class="author">
    <% if @article.user.picture? %>
      <%= link_to image_tag(@article.user.picture.url, class: "user-icon"), @article.user %>
    <% else %>
      <%= link_to image_tag('default_icon.png', class: "user-icon"), @article.user %>
    <% end %>
    <div class="user-in-charge">
      <div class="charge">営業担当</div> 
      <%= link_to "#{@article.user.name}", @article.user, {class: "user-name"} %>
    </div> 
  </div>
  
  <div class="content">
    <% text = safe_join(@article.content.split("\n"),tag(:br)) %>
    <%= text_url_to_link(text).html_safe %>
  </div>

  <div class="under_article">
    <div id="likes_buttons_<%= @article.id %>" >
      <%= render partial: 'likes/like', locals: { article: @article} %>
    </div>

    <div class="option">
      <%= "投稿日：#{@article.created_at.to_s(:datetime)}" %>
      <% if logged_in? %>
        <% if current_user.admin? || is_mine?(@article)  %>
            <%= link_to "編集", edit_article_path(@article) %>
            <%= link_to "削除", article_path(@article), method: :delete, data: {confirm: "記事を削除します。よろしいですか？"} unless current_user.test_user%>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="link_to_back"><%= link_to "一覧へ戻る", session[:forwarding_url] || root_url %></div>

</div>