config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  get    '/signup', to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get    '/feed',   to: 'articles#feed'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :articles do
    resource :likes, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article
  validates :user_id, presence: true
  validates :article_id, presence: true
  counter_culture :article
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :logged_in_user

  def create
    @article = Article.find(params[:article_id])
    liked = current_user.likes.build(article_id: params[:article_id])
    liked.save
    @article.reload
  end

  def destroy
    @article = Article.find(params[:article_id])
    liked = Like.find_by(article_id: params[:article_id], user_id: current_user.id)
    liked.destroy
    @article.reload
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<div class="likes_count">
  <% if logged_in?  %>
    <% if article.liked_by?(current_user) %>
      <%= link_to article_likes_path(article.id), class: "like_btn", method: :delete, remote: true do %>
        <i class="fas fa-heart like"></i>
      <% end %>
      <div class="counter"><%= article.likes_count %></div>
    <% else %>
      <%= link_to article_likes_path(article.id), class: "like_btn", method: :post, remote: true do %>
        <i class="fas fa-heart unlike"></i>
      <% end %>
      <div class="counter"><%= article.likes_count %></div>
    <% end %>
  <% else %>
    <%= link_to login_path, class: "like_btn" do %>
      <i class="fas fa-heart negative"></i>
    <% end %>
    <div class="counter"><%= article.likes_count %></div>
  <% end %>
</div>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @article.id %>').html("<%= j(render partial: 'likes/like', locals: {article: @article}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @article.id %>').html("<%= j(render partial: 'likes/like', locals: {article: @article}) %>");