config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  get    '/signup', to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get    '/feed',   to: 'articles#feed'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :articles do
    resource :likes, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  before_save { self.email = email.downcase }
  mount_uploader :picture, PictureUploader
  validates :name, presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validate :picture_size

  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Article.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  private

    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "画像は5MB以下のものを使用してください。")
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user,  only: [:edit, :update, :destroy, :following, :followers]
  before_action :correct_user,    only: [:edit, :update, :destroy]
  before_action :admin_check,     only: [:index]
  before_action :test_user_check, only: [:edit, :update, :destroy]
  before_action :store_location,  only: [:show]

  def index
    @users = User.order(:created_at).page(params[:page]).per(20)
  end

  def show
    @user = User.find(params[:id])
    @user_articles = @user.articles.includes([:category])
    @user_articles_pages = @user_articles.page(params[:page]).per(6)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user, notice: "ユーザー登録に成功しました"
    else
      render 'users/new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user, notice: "ユーザー情報を更新しました"
    else
      render 'users/edit'
    end
  end

  def destroy
    user = User.find(params[:id])
    if user.destroy
      flash[:notice] = "ユーザー「#{user.name}」は削除されました"
      if current_user.admin?
        redirect_to users_path
      else
        redirect_to root_url
      end
    else
      redirect_to user, notice: "ユーザー情報の削除に失敗しました"
    end
  end

  def following
    @title = "フォロー中"
    @user  = User.find(params[:id])
    @users = @user.following.page(params[:page]).per(20)
    render 'show_follow'
  end

  def followers
    @title = "フォロワー"
    @user  = User.find(params[:id])
    @users = @user.followers.page(params[:page]).per(20)
    render 'show_follow'
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation,
                                   :picture, :remove_picture)
    end

    def correct_user
      @user = User.find(params[:id])
      unless current_user?(@user) || current_user.admin?
        redirect_to root_url, notice: "このURLにはアクセスできません"
      end
    end

    def admin_check
      if !logged_in? || !current_user.admin?
        redirect_to root_url, notice: "adminユーザーのみアクセス可能です"
      end
    end

    def test_user_check
      user = User.find(params[:id])
      if user.test_user? && !current_user.admin?
        redirect_to user, notice: "テストユーザーの情報は編集できません"
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def total_likes(articles)
    articles.sum("likes_count")
  end
end

app/views/users/_delete_btn.html.erb
<% if logged_in? %>
  <% if current_user?(@user) && !current_user.admin? && !current_user.test_user? %>
    <p><%= link_to "退会する", user_path(@user), class: "btn-danger", method: :delete,
                              data: {confirm: "退会すると、投稿した記事も削除されます。よろしいですか？"} %></p>
  <% elsif !current_user?(@user) && current_user.admin? %>
    <p><%= link_to "ユーザーを削除する", user_path(@user), class: "btn-danger", method: :delete,
                                        data: {confirm: "ユーザー「#{@user.name}」を削除します。よろしいですか？"} %></p>
  <% end %>
<% end %>

app/views/users/_edit_logout_btn.html.erb
<div class="edit_logout" data-turbolinks="false">
  <% if logged_in? %>

    <% if (current_user?(@user) || current_user.admin?) && !current_user.test_user? %>
      <%= link_to "登録情報を編集する", edit_user_path(@user), class: "btn" %>
    <% end %>

    <% if current_user?(@user) %>
      <%= link_to logout_path , method: :delete, class: "btn-danger", data: {confirm: "ログアウトしますか？"} do %>
        <i class="fas fa-sign-out-alt"></i>ログアウト
      <% end %>
    <% end %>

  <% end %>
</div>

app/views/users/_follow.html.erb
<%= form_with model: current_user.active_relationships.build, remote: true do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "btn btn_follow" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_stats.html.erb
<div class="score">
  <div class="score_section">
    <div class="score_title">営業件数(記事数)</div> 
    <div class="total"><span><%= @user_articles.size %></span>件</div>
  </div>

  <div class="score_section">
    <div class="score_title">獲得いいね数</div> 
    <div class="total"><span><%= total_likes(@user_articles) %></span>件</div>
  </div>

  <div class="score_section">
    <div class="score_title">フォロー</div> 
    <div class="total"><span><%= link_to "#{@user.following.size}", following_user_path(@user), id: "following" %></span>人</div>
  </div>

  <div class="score_section">
    <div class="score_title">フォロワー</div> 
    <div class="total"><span><%= link_to "#{@user.followers.size}", followers_user_path(@user), id: "followers" %></span>人</div>
  </div>
</div>

app/views/users/_unfollow.html.erb
<%= form_with model: current_user.active_relationships.find_by(followed_id: @user.id), method: :delete, remote: true do |f| %>
  <%= f.submit "フォロー中", class: "btn  btn_unfollow" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "ユーザー情報の編集") %>

<div class="link_to_back_follow"><%= link_to "戻る", session[:forwarding_url] || root_url %></div>
<div class="section-title">ユーザー情報の編集</div> 

<div class="my_container">
  <%= form_with model: @user, local: true do |f| %>
    <p><%= render partial: 'shared/error_messages', locals: { object: f.object } %></p>

    <div class="my_container">
      <div class="user_info">
        <% if @user.picture? %>
          <%= image_tag @user.picture.url, id: :img_prev, class: "user-icon" %>
        <% else %>
          <%= image_tag 'default_icon.png', id: :img_prev, class: "user-icon" %>
        <% end %>

        <p><%= f.label :picture, "アイコンを選択", {class: 'choose_icon_btn'} %></p>
        <%= f.file_field :picture, id: :user_picture, accept: 'image/jpeg,image/gif,image/png' %>
        <script type="text/javascript">
          $(function() {
            function readURL(input) {
                if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
            $('#img_prev').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
                }
            }
            $("#user_picture").change(function(){
                readURL(this);
            });
          });
        </script>
        <div class="remove_checkbox">
          <%= f.check_box :remove_picture %>
          <label for="user_remove_picture">アイコンを削除する</label>
        </div>
      </div>
    </div>

    <%= f.label :name do %>
      <i class="fas fa-user"></i>ユーザー名
    <% end %>
    <%= f.text_field :name, placeholder: 'ユーザー名を入力' %>

    <%= f.label :email do %>
      <i class="fas fa-envelope"></i>メールアドレス
    <% end %>
    <%= f.text_field :email, placeholder: 'メールアドレスを入力' %>

    <%= f.label :password do %>
      <i class="fas fa-key"></i>パスワード(6文字以上)
    <% end %>
    <%= f.password_field :password, placeholder: '変更後のパスワードを入力' %>

    <%= f.label :password_confirmation do %>
      <i class="fas fa-key"></i>パスワードの再入力
    <% end %>
    <%= f.password_field :password_confirmation, placeholder: '変更後のパスワードを再入力' %>

    <%= f.submit "更新する", class: "btn" %>
  <% end %>
  <%= render 'delete_btn' %>
</div>

app/views/users/index.html.erb
<% provide(:title, "ユーザー一覧") %>

<div class="my_container">

  <div class="section-title">ユーザー一覧</div> 

  <% @users.each do |user| %>
    <div class="user_box">
      <div class="user">
        <% if user.picture? %>
          <%= link_to image_tag(user.picture.url, class: "user-icon"), user %>
        <% else %>
          <%= link_to image_tag('default_icon.png', class: "user-icon"), user %>
        <% end %>
          <%= link_to "#{user.name.truncate(10)}", user, {class: "user-name"} %>
      </div>
      <div class="delete">
        <% if !user.admin? %>
          <%= link_to "削除", user_path(user), method: :delete, data: {confirm: "ユーザー「#{user.name}」を削除します。よろしいですか？"} %>
        <% end %>
      </div>
    </div> 
    <%= paginate @users, window: 2, left: 1, right: 1 %>
  <% end %>

</div>

app/views/users/new.html.erb
<% provide(:title, "ユーザー登録") %>

<div class="my_container">
  <div class="test_login">
    <%= form_with scope: :session, url: login_path, local: true do |f| %>
      <%= f.hidden_field :email, value: 'test_user@sample.com' %>
      <%= f.hidden_field :password, value: 'test_user_foobar' %>
      <%= f.submit 'テストログイン', class: "test_login_btn",
                                     data: {confirm: "テストユーザーは\n「アイコン/登録情報の変更」「記事の削除」「退会」\nができません。"} %>
    <% end %>
  </div>

  <div class="form_area">
    <div class="section-title">ユーザー登録</div> 
    <%= form_with model: @user, local: true do |f| %>
      <p><%= render partial: 'shared/error_messages', locals: { object: f.object } %></p>

      <%= f.label :name do %>
        <i class="fas fa-user"></i>ユーザー名
      <% end %>
      <%= f.text_field :name, placeholder: 'ユーザー名を入力(30文字以内)' %>

      <%= f.label :email do %>
        <i class="fas fa-envelope"></i>メールアドレス
      <% end %>
      <%= f.text_field :email, placeholder: '例: test@sample.com' %>

      <%= f.label :password do %>
        <i class="fas fa-key"></i>パスワード
      <% end %>
      <%= f.password_field :password, placeholder: 'パスワードを入力(6文字以上)' %>

      <%= f.label :password_confirmation do %>
        <i class="fas fa-key"></i>パスワードを再入力
      <% end %>
      <%= f.password_field :password_confirmation, placeholder: 'もう一度パスワードを入力' %>

      <%= f.submit "登録する", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="my_container">
  <div class="user_info">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.picture? %>
      <%= image_tag @user.picture.url, class: "user-icon" %>
    <% else %>
      <%= image_tag 'default_icon.png', class: "user-icon" %>
    <% end %>

    <div class="user-name"><%= @user.name %></div>
    <%= render 'stats' %>
  </div>
  <%= render 'edit_logout_btn' %>
</div>

<div class="section-title">営業履歴</div> 
<%= render partial: 'shared/articles_grid', locals: { object: @user_articles_pages } %>
<%= paginate @user_articles_pages, window: 2, left: 1, right: 1 %>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>

<div class="my_container">

  <div class="link_to_back_follow"><%= link_to "戻る", session[:forwarding_url] || root_url %></div>
  <div class="section-title following-title"><%= "#{@user.name.truncate(10)}｜#{@title}" %></div> 

  <div class="no_following"><%= "該当のユーザーはいません" unless @users.present? %></div>

  <% @users.each do |user| %>
    <div class="user_box">
      <div class="user">
        <% if user.picture? %>
          <%= link_to image_tag(user.picture.url, class: "user-icon"), user %>
        <% else %>
          <%= link_to image_tag('default_icon.png', class: "user-icon"), user %>
        <% end %>
          <%= link_to "#{user.name.truncate(10)}", user, {class: "user-name"} %>
      </div>
    </div> 
    <%= paginate @users, window: 2, left: 1, right: 1 %>
  <% end %>

</div>