config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  get    '/signup', to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get    '/feed',   to: 'articles#feed'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :articles do
    resource :likes, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_alert.html.erb
<% if notice %>
  <div class="alert alert-info" data-testid="flash_message"><%= notice %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
  </div>
<% elsif alert %>
  <div class="alert alert-danger" data-testid="flash_message"><%= alert %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer-wrapper">
  <div class="page-footer">
    <ul>
      <li><%= link_to "TOPページへ", '/' %></li>
    </ul>
    <div class="footer-title">SALES-TALK</div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="page-header">
  <div class="header-menu">
    <%= link_to image_tag('logo.png', alt:'logo', class: "logo") , '/' %>
    <ul class="main-nav">
      <div class="nav-menu">

        <% if logged_in? %>
          <li>
            <%= link_to root_path, class: "nav-item"  do  %>
              <i class="fas fa-home"></i>ホーム
            <% end %>
          </li>
          <li>
            <%= link_to feed_path, class: "nav-item"  do  %>
              <i class="far fa-clock"></i>タイムライン
            <% end %>
          </li>
          <li>
            <%= link_to new_article_path, class: "nav-item"  do  %>
              <i class="fas fa-pencil-alt"></i>投稿
            <% end %>
          </li>
          <li>
            <% if current_user.picture? %>
              <%= link_to image_tag(current_user.picture.url, class: "user-icon"), current_user %>
            <% else %>
              <%= link_to image_tag('default_icon.png', class: "user-icon"), current_user %>
            <% end %>
          </li>
          <% if current_user.admin? %>
            <li><%= link_to "ユーザー一覧"  , users_path , class: "nav-item" %></li>
          <% end %>

        <% else %>
          <li>
            <%= link_to signup_path, class: "nav-item"  do  %>
               <i class="fas fa-user-plus"></i>新規登録
            <% end %>
          </li>
          <li>
            <%= link_to login_path, class: "nav-item"  do  %>
               <i class="fas fa-sign-in-alt"></i>ログイン
            <% end %>
          </li>
        <% end %>

      </div>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag('favicon.png') %>
    <title><%= full_title(yield(:title)) %> </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="twitter:card" content="summary_large_image"/>
    <meta name="twitter:site" content="@tom_tkyw"/>
    <meta property="og:url" content="https://www.sales-talk.net"/>
    <meta property="og:title" content="SALES TALK"/>
    <meta property="og:description" content="自分の好きなモノを紹介するwebサービス"/>
    <meta property="og:image" content="https://sales-talk-picture.s3-ap-northeast-1.amazonaws.com/+thumbnail/twitter_card.png"/> 
    <link href="https://fonts.googleapis.com/css?family=Kosugi+Maru|Noto+Sans+JP|Sawarabi+Mincho&display=swap" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="main">
      <%= render 'layouts/alert' %>
      <%= yield %>
    </div>
    <%= debug(params) if Rails.env.development? %>
    <%= render 'layouts/footer' %>
  </body>
</html>